create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_num text not null unique,
  status text not null default 'pending',
  customer_name text,
  customer_email text,
  phone text,
  address text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  shipping numeric(10,2) not null default 0,
  discount_pct integer,
  discount_amt numeric(10,2) not null default 0,
  coupon_code text,
  grand numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz
);

create index if not exists orders_status_confirmed_at_idx
  on public.orders (status, confirmed_at desc);

create index if not exists orders_created_at_idx
  on public.orders (created_at desc);
